export enum ROOT_ROUTES {
  BOTTOM_TAB_STACK = 'BOTTOM_TAB_STACK',
  HOME_STACK = 'HOME_STACK',
  AUTH_STACK = 'AUTH_STACK',
  PROFILE_STACK = 'PROFILE_STACK',
  WORKSHEET_STACK = 'WORKSHEET_STACK',
  TAKE_OFF_STACK = 'TAKE_OFF_STACK',
}
export enum BOTTOM_TAB_ROUTES {
  HOME = 'Bản đồ',
  ORDER = 'Đơn hàng',
  ACCOUNT = 'Tài khoản',
}
export enum HOME_ROUTES {
  NOTIFICATION = 'NOTIFICATION',
  NOTIFICATION_FILE = 'NOTIFICATION_FILE',
  INFO_NOTIFICATION = 'INFO_NOTIFICATION',
  CHECK_OUT_SUCCESS = 'CHECK_OUT_SUCCESS',
  SCAN_QR = 'SCAN_QR',
  CAMERA_CHECKIN = 'CAMERA_CHECKIN',
  CAMERA_CHECKOUT = 'CAMERA_CHECKOUT',
  CAMERA_SUPPORT_CHECKIN = 'CAMERA_SUPPORT_CHECKIN',
  CHECK_IN = 'CHECK_IN',
  CHECK_OUT = 'CHECK_OUT',
  COLLABORATOR = 'COLLABORATOR',
  INFO_COLLABORATOR = 'INFO_COLLABORATOR',
  ADD_COLLABORATOR = 'ADD_COLLABORATOR',
  REQUEST = 'REQUEST',
}
export enum AUTH_ROUTES {
  LOGIN = 'LOGIN',
  REGISTER = 'REGISTER',
  REGISTER_PERSONAL_INFO = 'REGISTER_PERSONAL_INFO',
  REGISTER_POLICY = 'REGISTER_POLICY',
  REGISTER_OTHER = 'REGISTER_OTHER',
  REGISTER_SUCCESS = 'REGISTER_SUCCESS',
  CAMERA_CCCD = 'CAMERA_CCCD',
  CAMERA_AVATAR = 'CAMERA_AVATAR',
  SCAN_CCCD = 'SCAN_CCCD',
}

export enum PROFILE_ROUTES {
  ACCOUNT_INFO = 'ACCOUNT_INFO',
  CHANGE_PASSWORD = 'CHANGE_PASSWORD',
  UPDATE_PROFILE = 'UPDATE_PROFILE',
  REVENUA_INFO = "REVENUA_INFO",
  FONT_SIZE = 'FONT_SIZE',
  SUPPORT = 'SUPPORT',
  REQUEST_SUPPORT = 'REQUEST_SUPPORT',
  LIST_TECHNICIAN = 'LIST_TECHNICIAN',

}
